### ISSUE TITLE
Finish Cleaning HPS and PAGL to Match

### ISSUE THREAD

**Issue by melaniemilligan** [alf10087/SLASP#25]

**Comment by melaniemilligan** [comment]
@alf10087 make anxiety index

**Comment by melaniemilligan** [comment]
@alf10087 make a mental health services variable with 1 (got them) and 0 (didn't get them) in PAGL

**Comment by melaniemilligan** [comment]
@alf10087 I don't see the lives_alone variable in the HPS data set, but we had it at some point. Need to figure out where it is and match it with PAGL's "lives_alone"

**Comment by melaniemilligan** [comment]
@alf10087 Finalize whether we want to match anything with PAGL variables "overall_mental_health" and "financial_stress"

**Comment by melaniemilligan** [comment]
@alf10087 Are we going to match EST_MSA with anything in PAGL? I can create a variable, just let me know!

**Comment by arojasalvarez** [comment]
> @alf10087 make anxiety index

Okay, I made this index, but we'll still have to use just anxiety in PAGL for this question, and think what is the best way to match the index from our survey.

**Comment by arojasalvarez** [comment]
> @alf10087 make a mental health services variable with 1 (got them) and 0 (didn't get them) in PAGL

I can't generate this since I don't have the originating file from PAGL, and the one uploaded here is already clean. I'll do it for HPS.

**Comment by arojasalvarez** [comment]
> @alf10087 I don't see the lives_alone variable in the HPS data set, but we had it at some point. Need to figure out where it is and match it with PAGL's "lives_alone"

It's called "alone", just fixed it and renamed it lives_alone.

**Comment by arojasalvarez** [comment]
> @alf10087 Are we going to match EST_MSA with anything in PAGL? I can create a variable, just let me know!

Let's do the same we did with states, add a new number not already in the list, and assign Austin as XXXX MSA and CDMX as YYY MSA.

**Comment by melaniemilligan** [comment]
Added mh_services and EST_MSA to PAGL
