### ISSUE TITLE
Merge HPS and PAGL

### ISSUE THREAD

**Issue by arojasalvarez** [alf10087/SLASP#6]

**Comment by arojasalvarez** [comment]
hispanic <> RHISPANIC
RRACE <> race
TTHLD_NUMPER <> alone

**Comment by arojasalvarez** [comment]
age <> TBIRTH_YEAR

Transform TBIRTH_YEAR into age (done).

**Comment by melaniemilligan** [comment]
change gender to female and have it 0 or 1 (done)

**Comment by melaniemilligan** [comment]
change hispanic in PAGL to 1 or 0 (done)

@alf10087 change RHISPANIC to hispanic and code the same way

**Comment by arojasalvarez** [comment]
@melaniemilligan mutate(educ = 4) (done)
@alf10087 rename(EEDUC = educ)

**Comment by arojasalvarez** [comment]
Drop MS @alf10087

**Comment by arojasalvarez** [comment]
lives alone for alfonso is based on household number @alf10087 
remove lives_roommates and lives_family from PAGL data set and change lives_alone to 0 or 1 @melaniemilligan (done)

**Comment by melaniemilligan** [comment]
had_covid to be 1 or 0 (done)

**Comment by melaniemilligan** [comment]
scale PAS_mean * .8 and give it new name --> anxious (done)

**Comment by melaniemilligan** [comment]
@alf10087 make index out of DOWN, INTEREST, ANXIOUS, and WORRY --> called "anxious"

**Comment by melaniemilligan** [comment]
change resources_medication to prescription and 0 or 1 (done)
@alf10087 make PRESCRIPT binary and change name to prescription

**Comment by melaniemilligan** [comment]
@melaniemilligan add variable to PAGL data about someone in network having covid --> call it network_covid

@alf10087 make sure this matches HPS

**Comment by melaniemilligan** [comment]
@melaniemilligan create a value called region --> values are mexico (6) and texas (5) (done)

**Comment by melaniemilligan** [comment]
remove variables not in use in PAGL data set @melaniemilligan 

remove variables not in use in HPS data set @alf10087

**Comment by melaniemilligan** [comment]
@melaniemilligan change is_employed to binary and call it "employed"
@alf10087 create binary employment variable

* we didn't talk about this but I think it can be done

**Comment by melaniemilligan** [comment]
@alf10087 rename HPS race variable to be "race"
