### ISSUE TITLE
Clean PAGL variables

### ISSUE THREAD

**Issue by arojasalvarez** [alf10087/SLASP#7]

**Comment by arojasalvarez** [comment]
For each variable we're keeping, let's do this:

```{r}
1. Make sure it is a factor

2. Table(variable)

3. Histogram(variable)  

4. str(Variable) 
```

**Comment by melaniemilligan** [comment]
PAGL variables I'm including:

1. university
2.  age (to match with TBIRTH_YEAR)
3. gender (to match with EGENDER)
4. ethnicity (to match RHISPANIC) - only in English data
5. race (to match RRACE)
6. academic year?
7. who they live with (to possibly match THHLD_NUMADLT/KID?)
8. respondent_covid (to match HADCOVID) - also included severity and whether they had to move b/c of the pandemic
9. is_employed (to match ANYWORK)
10. All PAS variables (to match ANXIOUS, WORRY, INTEREST, DOWN)
11. overall_mental_health (to match ANXIOUS, WORRY, INTEREST, DOWN)
12. mental health resources (to match PRESCRIPT, MH_SVCS, MH_NOTGET)
13. living_situation (to match TENURE, LIVQTRRV)
14. financial_stress (to match EVICT)

**Comment by melaniemilligan** [comment]
https://rpubs.com/melaniemilligan/SLAS-PAGL-Clean-Vars

**Comment by melaniemilligan** [comment]
need help with lives_with and race variables
